name: delete-vercel-preview-urls
description: delete public Vercel Preview urls if remote branch is deleted.
author: Hiroki Miyaji
inputs:
  vercelToken:
    description: Vercel token.
    required: true
  vercelProjectId:
    description: Vercel project id. I recommend to set this parameter.
    default: ""
    required: false

branding:
  icon: "trash-2"
  color: "gray-dark"

runs:
  using: node16
  main: src/main.js
